controllers/TestController.php
<?php
namespace frontend\controllers;

use common\models\database\TestValues;
use common\models\database\Test;
use common\models\database\Question;
use common\models\database\TestValuesMatrix;
use frontend\models\TestResults;
use Yii;
use yii\web\Controller;
use yii\web\Session;
use yii\db\Query;
use yii\filters\VerbFilter;
use yii\data\ArrayDataProvider;

/**
 * Site controller
 */
class TestController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }
    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        Yii::$app->view->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js', ['depends' => 'yii\web\YiiAsset']);
        Yii::$app->view->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/flexie/1.0.3/flexie.min.js', ['depends' => 'yii\web\YiiAsset']);
        Yii::$app->view->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.16/css/bulma.min.css');
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css');

        $model = Test::find()->where(['sort' => 1])->all();
        return $this->render('_textimage', [
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionInittest($id)
    {
        $testModel = Test::findOne($id);

        $session = Yii::$app->session;
        if (!$session->isActive) {
            $session->open();
        }

        $tests = $session->get('tests');

        $tests[$id]['type'] = $testModel->getAttribute('result_type_id') == 3 ? 1 : 0;
        $tests[$id]['test_offset'] = 0;
        $tests[$id]['test_passed'] = 0;

        if ($tests[$id]['type']) {
            $tests[$id]['test_quantity'] = count($testModel->testReferences);
            foreach ($testModel->testReferences as $key => $test) {
                $tests[$id]['tests'][$key]['test_id'] = $test->getAttribute('test_child_id');
                $tests[$id]['tests'][$key]['passed_questions'] = 0;
                $tests[$id]['tests'][$key]['answewrs'] = [];
                $tests[$id]['tests'][$key]['answewrsid'] = [];
            }
        } else {
            $tests[$id]['test_quantity'] = 1;
            $tests[$id]['tests'][0]['test_id'] = $id;
            $tests[$id]['tests'][0]['passed_questions'] = 0;
            $tests[$id]['tests'][0]['answewrs'] = [];
            $tests[$id]['tests'][0]['answewrsid'] = [];
        }

        $session->set('tests', $tests);
        $session->set('current_test', $id);
        //$session->remove('current_tests');
        $session->close();

        return $this->redirect(['test', 'number' => 1]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionTest($number)
    {

        Yii::$app->view->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js', ['depends' => 'yii\web\YiiAsset']);
        Yii::$app->view->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/flexie/1.0.3/flexie.min.js', ['depends' => 'yii\web\YiiAsset']);
        Yii::$app->view->registerJsFile('js/jquery.cropit.js', ['depends' => 'frontend\assets\AppAsset']);

        Yii::$app->view->registerJsFile('js/scripts.js', ['depends' => 'frontend\assets\AppAsset']);
        Yii::$app->view->registerJsFile('js/custom.js', ['depends' => 'frontend\assets\AppAsset']);

        Yii::$app->view->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.16/css/bulma.min.css');
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css');

        $session = Yii::$app->session;
        if (!$session->isActive) {
            $session->open();
        }

        $currentTest = $session->get('current_test');
        $tests = $session->get('tests');
//        var_dump($currentTest);
//        var_dump($tests[0]['tests'][0]['test_id']);
//        die();
        //Check if not equal zero or empty
        if (!$number || !$tests || !$currentTest) {
            $session->close();
            return $this->redirect(['site/list-test']);
        }

        $passedQuestions = $tests[$currentTest]['tests'][$tests[$currentTest]['test_offset']]['passed_questions'];


        //Check if $require number is more the
        if ($passedQuestions + 2 < $number) {
            $session->close();
            return $this->actionTest($passedQuestions + 1);
        }
        $questionsQuantity = count(Test::findOne($tests[$currentTest]['tests'][$tests[$currentTest]['test_offset']]['test_id'])->question);


        //if isset post
        if (Yii::$app->request->post()) {
            $answewrs = $tests[$currentTest]['tests'][$tests[$currentTest]['test_offset']]['answewrs'];
            $answewrsid = $tests[$currentTest]['tests'][$tests[$currentTest]['test_offset']]['answewrsid'];
            $answewrs[$number - 1] = Yii::$app->request->post('answer');
            $answewrsid[Yii::$app->request->post('answewrid')] = $number - 1;
            $tests[$currentTest]['tests'][$tests[$currentTest]['test_offset']]['answewrs'] = $answewrs;
            $tests[$currentTest]['tests'][$tests[$currentTest]['test_offset']]['answewrsid'] = $answewrsid;
            $tests[$currentTest]['tests'][$tests[$currentTest]['test_offset']]['passed_questions'] = $number - 1;
            $session->set('tests', $tests);
        }


        //if test has been passed
        if ($number > $questionsQuantity) {
            if ($tests[$currentTest]['test_offset'] + 1 < $tests[$currentTest]['test_quantity']) {
                $tests[$currentTest]['test_offset']++;
                $tests[$currentTest]['test_passed'] = 1;
                $session->set('tests', $tests);
                return $this->actionTest(1);
            }
//            if(Yii::$app->user->isGuest){
//                return $this->redirect(['/payment/registration']);
//            }

            return $this->redirect(['/payment/invoice', 'test' => $currentTest]);
//            return $this->redirect(['/test/result', 'test' => $currentTest]);
        }

        $questionModel = Question::find()->where(['test_id' => $tests[$currentTest]['tests'][$tests[$currentTest]['test_offset']]['test_id']])->orderBy('priority')->offset($number - 1)->one();
        return $this->getQuestionSwith($questionModel, $number, $questionsQuantity);
    }

    /**
     * Switch form tampale when create new answers
     * @param object $model (model of Answer record)
     * @return mixed
     */
    protected function getQuestionSwith($model, $questionNumber, $questionsQuantity)
    {
        Yii::$app->view->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js', ['depends' => 'yii\web\YiiAsset']);
        Yii::$app->view->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/flexie/1.0.3/flexie.min.js', ['depends' => 'yii\web\YiiAsset']);
        Yii::$app->view->registerJsFile('js/jquery.cropit.js', ['depends' => 'frontend\assets\AppAsset']);

        Yii::$app->view->registerJsFile('js/main.js', ['depends' => 'frontend\assets\AppAsset']);
        Yii::$app->view->registerJsFile('js/custom.js', ['depends' => 'frontend\assets\AppAsset']);

        Yii::$app->view->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.16/css/bulma.min.css');
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css');
        //meta
        Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => $model->test->getAttribute('meta_description')]);
        Yii::$app->view->registerMetaTag(['name' => 'title', 'content' => $model->test->getAttribute('meta_title')]);
        Yii::$app->view->registerMetaTag(['name' => 'keys', 'content' => $model->test->getAttribute('meta_keys')]);

        switch ($model->questionType->getAttribute('slug')) {
            case 'sympleText':
                return $this->render('_sympletext', [
                    'model' => $model,
                    'currentQuestion' => $questionNumber,
                    'questionsQuantity' => $questionsQuantity
                ]);
                break;
            case 'sympleImage':
                return $this->render('_sympleimage', [
                    'model' => $model,
                    'currentQuestion' => $questionNumber,
                    'questionsQuantity' => $questionsQuantity
                ]);
                break;
            case 'textImage':
                return $this->render('_textimage', [
                    'model' => $model,
                    'currentQuestion' => $questionNumber,
                    'questionsQuantity' => $questionsQuantity
                ]);
                break;
            case 'skinColor':
                return $this->render('_skincolor', [
                    'model' => $model,
                    'currentQuestion' => $questionNumber,
                    'questionsQuantity' => $questionsQuantity
                ]);
                break;
            case 'aboutMeColour':
                return $this->render('_aboutmecolour', [
                    'model' => $model,
                    'currentQuestion' => $questionNumber,
                    'questionsQuantity' => $questionsQuantity
                ]);
                break;
            case 'aboutMeTwo':
                return $this->render('_aboutmetwo', [
                    'model' => $model,
                    'currentQuestion' => $questionNumber,
                    'questionsQuantity' => $questionsQuantity
                ]);
                break;
            case 'aboutMeOne':
                return $this->render('_aboutmeone', [
                    'model' => $model,
                    'currentQuestion' => $questionNumber,

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $name;
?>
<?= $this->render('/_block/_header'); ?>
<section class="test-list">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="site-error">

                <h1><?= Html::encode($this->title) ?></h1>

                <div class="alert alert-danger">
                    <?= nl2br(Html::encode($message)) ?> <?= Html::a("На главную >>",Url::home()); ?>
                </div>

                <p>
                    The above error occurred while the Web server was processing your request.
                </p>
                <p>
                    Please contact us if you think this is a server error. Thank you.
                </p>

            </div>
        </div>
    </div>
</section>

views/site/female-test.php
<?php
use yii\helpers\Url;
use common\models\database\Gallery;
use common\models\search\Discount;

/**
 * Created by IntelliJ IDEA.
 * User: sandro
 * Date: 29.04.16
 * Time: 23:45
 */

/* @var $this yii\web\View */

$this->title = 'Корпорация Имиджа | Список тестов';
?>
    <!--[if IE]>
    <script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<?= $this->render('/_block/_header'); ?>

    <section class="pad-top-more head-marg">
        <h1 class="page-title">Вы - персональный имиджмейкер</h1>
        <div class="container">
            <div class="columns is-multiline pad-top-more test-box-more">
                <!-- wedd tests-->
                <div class="female-tests">
                    <?php
                    foreach ($female as $item) {
                        echo '<div class="column is-8 is-offset-2 pad-top">';
                        echo '<div class="card wide">';
                        echo '<div class="card-image">';
                        echo '<figure class="relative image tests-img card-img-size">';
                        echo '<img src="'.Gallery::findOne(['id' => $item->img])->src.'" alt="'.Gallery::findOne(['id' => $item->img])->alt.'" title="'.Gallery::findOne(['id' => $item->img])->title.'">';
                        echo '<div class="is-overlay prices">';
                        if(Discount::findOne(['id_test' => $item->id, 'status' => 1])){
                            echo '<span class="old-price">'.$item->price.'</span>';
                            echo Discount::findOne(['id_test' => $item->id, 'status' => 1])->amount.'р</div>';
                        }
                        else{
                            echo $item->price.'р</div>';
                        }
                        // echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['/payment/index', 'test' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';

                        echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['test/inittest', 'id' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';
                        echo '</figure>';
                        echo '</div>';
                        echo '<div class="card-content">';
                        echo '<div class="media">';
                        echo '<div class="media-left">';
                        echo '<span>'.$item->title.'</span>';
                        echo '</div>';
                        echo '<div class="media-content is-text-right">';
                        echo '<img src="/theme/img/like_pink.png" alt=""><span class="like pink">'.$item->like.'</span>';
                        echo '</div>';
                        echo '</div>';
                        echo '<div class="text">';
                        echo $item->description;
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                    }
                    ?>
                </div>
                <!-- end wedd tests-->

            </div>
            <div class="is-text-centered"><a href="#" class="prima-btn btn-more">Загрузить еще</a></div>
        </div>
    </section>


<?= $this->render('/_block/_footer'); ?>

views/site/list-test.php
<?php

use yii\helpers\Url;
use common\models\database\Gallery;
use common\models\search\Discount;

/**
 * Created by IntelliJ IDEA.
 * User: sandro
 * Date: 29.04.16
 * Time: 23:45
 */

/* @var $this yii\web\View */

$this->title = 'Корпорация Имиджа | Список тестов';
?>
    <!--[if IE]>
    <script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<?= $this->render('/_block/_header'); ?>

<section class="pad-top-more head-marg">
    <h1 class="page-title">Вы - персональный имиджмейкер</h1>
    <div class="container">
        <div class="is-text-centered tests-btns">
            <button type="button" class="toggle-tab lips">Женщина</button>
            <button type="button" class="toggle-tab usi">Мужчина</button>
            <button type="button" class="toggle-tab wedd">Свадьба</button>
        </div>
        <div class="columns is-multiline pad-top-more test-box-more">
            <!-- female tests-->
            <div class="female-tests">
                <?php
                    foreach ($female as $item) {
                        echo '<div class="column is-8 is-offset-2 pad-top">';
                        echo '<div class="card wide">';
                        echo '<div class="card-image">';
                        echo '<figure class="relative image tests-img card-img-size">';
                        echo '<img src="'.Gallery::findOne(['id' => $item->img])->src.'" alt="'.Gallery::findOne(['id' => $item->img])->alt.'" title="'.Gallery::findOne(['id' => $item->img])->title.'">';
                        echo '<div class="is-overlay prices">';
                        if(Discount::findOne(['id_test' => $item->id, 'status' => 1])){
                            echo '<span class="old-price">'.$item->price.'</span>';
                            echo Discount::findOne(['id_test' => $item->id, 'status' => 1])->amount.'р</div>';
                        }
                        else{
                            echo $item->price.'р</div>';
                        }
                       // echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['/payment/index', 'test' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';
                        
                        echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['test/inittest', 'id' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';
                        echo '</figure>';
                        echo '</div>';
                        echo '<div class="card-content">';
                        echo '<div class="media">';
                        echo '<div class="media-left">';
                        echo '<span>'.$item->title.'</span>';
                        echo '</div>';
                        echo '<div class="media-content is-text-right">';
                        echo '<img src="/theme/img/like_pink.png" alt=""><span class="like pink">'.$item->like.'</span>';
                        echo '</div>';
                        echo '</div>';
                        echo '<div class="text">';
                        echo $item->description;
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                    }
                ?>
            </div>
            <!-- end female tests-->
            <!-- male tests-->
            <div class="male-tests hide-tab">
                <?php
                    foreach ($male as $item) {
                        echo '<div class="column is-8 is-offset-2 pad-top">';
                        echo '<div class="card wide">';
                        echo '<div class="card-image">';
                        echo '<figure class="relative image tests-img card-img-size">';
                        echo '<img src="'.Gallery::findOne(['id' => $item->img])->src.'" alt="'.Gallery::findOne(['id' => $item->img])->alt.'" title="'.Gallery::findOne(['id' => $item->img])->title.'">';
                        echo '<div class="is-overlay prices">';
                        if(Discount::findOne(['id_test' => $item->id, 'status' => 1])){
                            echo '<span class="old-price">'.$item->price.'</span>';
                            echo Discount::findOne(['id_test' => $item->id, 'status' => 1])->amount.'р</div>';
                        }
                        else{
                            echo $item->price.'р</div>';
                        }
                        echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['test/inittest', 'id' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';
                        echo '</figure>';
                        echo '</div>';
                        echo '<div class="card-content">';
                        echo '<div class="media">';
                        echo '<div class="media-left">';
                        echo '<span>'.$item->title.'</span>';
                        echo '</div>';
                        echo '<div class="media-content is-text-right">';
                        echo '<img src="/theme/img/like_pink.png" alt=""><span class="like pink">'.$item->like.'</span>';
                        echo '</div>';
                        echo '</div>';
                        echo '<div class="text">';
                        echo $item->description;
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                    }
                ?>
            </div>
            <!-- end male tests-->
            <!-- wedd tests-->
            <div class="wedd-tests hide-tab">
                <?php
                    foreach ($wedd as $item) {
                        echo '<div class="column is-8 is-offset-2 pad-top">';
                        echo '<div class="card wide">';
                        echo '<div class="card-image">';
                        echo '<figure class="relative image tests-img card-img-size">';
                        echo '<img src="'.Gallery::findOne(['id' => $item->img])->src.'" alt="'.Gallery::findOne(['id' => $item->img])->alt.'" title="'.Gallery::findOne(['id' => $item->img])->title.'">';
                        echo '<div class="is-overlay prices">';
                        if(Discount::findOne(['id_test' => $item->id, 'status' => 1])){
                            echo '<span class="old-price">'.$item->price.'</span>';
                            echo Discount::findOne(['id_test' => $item->id, 'status' => 1])->amount.'р</div>';
                        }
                        else{
                            echo $item->price.'р</div>';
                        }
                        echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['test/inittest', 'id' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';
                        echo '</figure>';
                        echo '</div>';
                        echo '<div class="card-content">';
                        echo '<div class="media">';
                        echo '<div class="media-left">';
                        echo '<span>'.$item->title.'</span>';
                        echo '</div>';
                        echo '<div class="media-content is-text-right">';
                        echo '<img src="/theme/img/like_pink.png" alt=""><span class="like pink">'.$item->like.'</span>';
                        echo '</div>';
                        echo '</div>';
                        echo '<div class="text">';
                        echo $item->description;
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                    }
                ?>
            </div>
            <!-- end wedd tests-->
        </div>
        <div class="is-text-centered"><a href="#" class="prima-btn btn-more">Загрузить еще</a></div>
    </div>
</section>


<?= $this->render('/_block/_footer'); ?>

views/site/male-test.php
<?php
use yii\helpers\Url;
use common\models\database\Gallery;
use common\models\search\Discount;

/**
 * Created by IntelliJ IDEA.
 * User: sandro
 * Date: 29.04.16
 * Time: 23:45
 */

/* @var $this yii\web\View */

$this->title = 'Корпорация Имиджа | Список тестов';
?>
    <!--[if IE]>
    <script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<?= $this->render('/_block/_header'); ?>

    <section class="pad-top-more head-marg">
        <h1 class="page-title">Вы - персональный имиджмейкер</h1>
        <div class="container">
            <div class="columns is-multiline pad-top-more test-box-more">
                <!-- wedd tests-->
                <div class="female-tests">
                    <?php
                    foreach ($male as $item) {
                        echo '<div class="column is-8 is-offset-2 pad-top">';
                        echo '<div class="card wide">';
                        echo '<div class="card-image">';
                        echo '<figure class="relative image tests-img card-img-size">';
                        echo '<img src="'.Gallery::findOne(['id' => $item->img])->src.'" alt="'.Gallery::findOne(['id' => $item->img])->alt.'" title="'.Gallery::findOne(['id' => $item->img])->title.'">';
                        echo '<div class="is-overlay prices">';
                        if(Discount::findOne(['id_test' => $item->id, 'status' => 1])){
                            echo '<span class="old-price">'.$item->price.'</span>';
                            echo Discount::findOne(['id_test' => $item->id, 'status' => 1])->amount.'р</div>';
                        }
                        else{
                            echo $item->price.'р</div>';
                        }
                        // echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['/payment/index', 'test' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';

                        echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['test/inittest', 'id' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';
                        echo '</figure>';
                        echo '</div>';
                        echo '<div class="card-content">';
                        echo '<div class="media">';
                        echo '<div class="media-left">';
                        echo '<span>'.$item->title.'</span>';
                        echo '</div>';
                        echo '<div class="media-content is-text-right">';
                        echo '<img src="/theme/img/like_pink.png" alt=""><span class="like pink">'.$item->like.'</span>';
                        echo '</div>';
                        echo '</div>';
                        echo '<div class="text">';
                        echo $item->description;
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                    }
                    ?>
                </div>
                <!-- end wedd tests-->

            </div>
            <div class="is-text-centered"><a href="#" class="prima-btn btn-more">Загрузить еще</a></div>
        </div>
    </section>


<?= $this->render('/_block/_footer'); ?>

views/site/wedd-test.php
<?php

use yii\helpers\Url;
use common\models\database\Gallery;
use common\models\search\Discount;

/**
 * Created by IntelliJ IDEA.
 * User: sandro
 * Date: 29.04.16
 * Time: 23:45
 */

/* @var $this yii\web\View */

$this->title = 'Корпорация Имиджа | Список тестов';
?>
    <!--[if IE]>
    <script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<?= $this->render('/_block/_header'); ?>

    <section class="pad-top-more head-marg">
        <h1 class="page-title">Вы - персональный имиджмейкер</h1>
        <div class="container">
            <div class="columns is-multiline pad-top-more test-box-more">
                <!-- wedd tests-->
                <div class="female-tests">
                    <?php
                    foreach ($wedd as $item) {
                        echo '<div class="column is-8 is-offset-2 pad-top">';
                        echo '<div class="card wide">';
                        echo '<div class="card-image">';
                        echo '<figure class="relative image tests-img card-img-size">';
                        echo '<img src="'.Gallery::findOne(['id' => $item->img])->src.'" alt="'.Gallery::findOne(['id' => $item->img])->alt.'" title="'.Gallery::findOne(['id' => $item->img])->title.'">';
                        echo '<div class="is-overlay prices">';
                        if(Discount::findOne(['id_test' => $item->id, 'status' => 1])){
                            echo '<span class="old-price">'.$item->price.'</span>';
                            echo Discount::findOne(['id_test' => $item->id, 'status' => 1])->amount.'р</div>';
                        }
                        else{
                            echo $item->price.'р</div>';
                        }
                        // echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['/payment/index', 'test' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';

                        echo '<a class="is-overlay hover-gray" href="'.Url::toRoute(['test/inittest', 'id' => $item->id]).'">ПРОЙТИ ТЕСТ</a>';
                        echo '</figure>';
                        echo '</div>';
                        echo '<div class="card-content">';
                        echo '<div class="media">';
                        echo '<div class="media-left">';
                        echo '<span>'.$item->title.'</span>';
                        echo '</div>';
                        echo '<div class="media-content is-text-right">';
                        echo '<img src="/theme/img/like_pink.png" alt=""><span class="like pink">'.$item->like.'</span>';
                        echo '</div>';
                        echo '</div>';
                        echo '<div class="text">';
                        echo $item->description;
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                        echo '</div>';
                    }
                    ?>
                </div>
                <!-- end wedd tests-->

            </div>
            <div class="is-text-centered"><a href="#" class="prima-btn btn-more">Загрузить еще</a></div>
        </div>
    </section>


<?= $this->render('/_block/_footer'); ?>