controllers/BlogController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\database\Blog;
use common\models\database\BlogCategory;

class BlogController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css');
        Yii::$app->view->registerJsFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js', ['depends' => 'yii\web\YiiAsset']);
        Yii::$app->view->registerJsFile('js/scripts.js', ['depends' => 'frontend\assets\AppAsset']);
        $query = Blog::find();
        if(Yii::$app->request->get('category') && BlogCategory::findOne(['category_alias' => Yii::$app->request->get('category')])){
            $query->where(['category' => BlogCategory::findOne(['category_alias' => Yii::$app->request->get('category')])->id]);
        }
        $model = $query->all();
        $popular = $query->limit(4)->orderBy(['like' => SORT_DESC])->all();
        return $this->render('index',[
            'blog' => $model,
            'popular' => $popular,
            'category' => Yii::$app->request->get('category'),
        ]);
    }

    public function actionView()
    {
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css');
        Yii::$app->view->registerJsFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js', ['depends' => 'yii\web\YiiAsset']);
        if(Yii::$app->request->get('element') && Blog::findOne(['alias' => Yii::$app->request->get('element')])){
            $model = Blog::findOne(['alias' => Yii::$app->request->get('element')]);

            $views = $model->getAttribute('views')?$model->getAttribute('views'):0;
            $model->setAttribute("views", $views+1);
            $model->save();

            $also = Blog::find()->where(['category' => $model->category])->limit(3)->all();

            //meta
            Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => $model->getAttribute('meta_description')]);
            Yii::$app->view->registerMetaTag(['name' => 'title', 'content' => $model->getAttribute('meta_title')]);
            Yii::$app->view->registerMetaTag(['name' => 'keys', 'content' => $model->getAttribute('meta_keys')]);
        }
        else {
            throw new \yii\web\NotFoundHttpException("Статья не найдена!");
        }
        return $this->render('view',[
               'model' => $model,
               'also' => $also,
           ]);
    }
}

controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\database\Content;
use common\models\database\Gallery;
use common\models\database\Slider;
use Yii;
use common\models\database\Order;
use yii\web\Controller;
use common\models\database\Test;
use common\models\database\Blog;
use dektrium\user\models\LoginForm;
use dektrium\user\models\RegistrationForm;
use dektrium\user\models\User;
use frontend\models\UserComments;
use frontend\models\TestResults;
use frontend\models\Auth;
use yii\helpers\Url;
use common\models\database\User as Acc;
use common\models\main\DataOrder;
use frontend\models\Refer;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public function actions()
    {
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css');
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ]
        ];
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
//        $session = Yii::$app->session;
//        var_dump($session['partner_id'] );
//        die();
        $request = Yii::$app->request;
        if ($request->get() != null) {
            $this->usePartner(key($request->get()));
        }
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css');
//        Yii::$app->view->registerJsFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js', ['depends' => 'yii\web\YiiAsset']);

        $model = Test::find()->orderBy('sort')->limit(3)->all();
        $slider = [];
        foreach (unserialize(Slider::findOne(['id' => 2])->image_id) as $key => $item) {
            $slider[$key] = Gallery::findOne(['id' => $item])->src;
        }
        $aboutUs = Content::findOne(['id' => 1]);
//        var_dump($aboutUs);die;
        //meta
        Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => $aboutUs->getAttribute('meta_description')]);
        Yii::$app->view->registerMetaTag(['name' => 'title', 'content' => $aboutUs->getAttribute('meta_title')]);
        Yii::$app->view->registerMetaTag(['name' => 'keys', 'content' => $aboutUs->getAttribute('meta_keys')]);
        $blog = Blog::find()->limit(3)->all();
        $comments = UserComments::find()
            ->where(['status' => 1])
            ->orderBy('id DESC')
            ->all();
        return $this->render('index', [
            'model' => $model,
            'slider' => $slider,
            'comments' => $comments,
            'content' => [$aboutUs],
            'blog' => $blog
        ]);
    }

    public function actionMyTests()
    {
        Yii::$app->view->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.16/css/bulma.min.css');
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css');
        if (!Yii::$app->user->isGuest) {
            $temp_user_ids_tests = TestResults::selectResults();
            $temp_user_ids_paid_tests = $this->selectIdForPaidOrders();
            $user_ids_tests = $temp_user_ids_tests ? array_column($temp_user_ids_tests, 'id_test') : [];
            $user_ids_paid_tests = $temp_user_ids_paid_tests ? array_unique(array_column($temp_user_ids_paid_tests, 'for')) : [];
            unset($temp_user_ids_paid_tests);
            unset($temp_user_ids_tests);
            $user_tests = $this->selectUserTests($user_ids_tests);
            $finished_tests = array();
            $unfinished_tests = array();
            foreach ($user_tests as $user_test) {
                if (in_array($user_test['id'], $user_ids_tests)) {
//                if (in_array($user_test['id'], $user_ids_paid_tests))
                    if (in_array($user_test['id'], $user_ids_paid_tests))
                        $user_test['status'] = 'paid';
                    else
                        $user_test['status'] = 'unpaid';
                    array_push($finished_tests, $user_test);
                } else array_push($unfinished_tests, $user_test);
            }
            unset($user_tests);
            return $this->render('my-tests', [
                'finished_tests' => $finished_tests,
                'unfinished_tests' => $unfinished_tests,
            ]);
        } else {
            return $this->redirect(['site/index']);
        }
    }

    public function actionListTest()
    {
        Yii::$app->view->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.16/css/bulma.min.css');
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css');
        $female = Test::find()->where(['type' => 1])->orderBy(['sort' => SORT_DESC])->all();
        $male = Test::find()->where(['type' => 2])->orderBy(['sort' => SORT_DESC])->all();
        $wedd = Test::find()->where(['type' => 3])->orderBy(['sort' => SORT_DESC])->all();

        $seoBlock = Content::findOne(['id' => 2]);
        //meta
        Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => $seoBlock->getAttribute('meta_description')]);
        Yii::$app->view->registerMetaTag(['name' => 'title', 'content' => $seoBlock->getAttribute('meta_title')]);
        Yii::$app->view->registerMetaTag(['name' => 'keys', 'content' => $seoBlock->getAttribute('meta_keys')]);

        return $this->render('list-test', [
            'female' => $female,
            'male' => $male,
            'wedd' => $wedd,
            'seoBlock' => $seoBlock,
        ]);
    }

    public function actionWeddTest()
    {
        Yii::$app->view->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.16/css/bulma.min.css');
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css');
        $wedd = Test::find()->where(['type' => 3])->orderBy(['sort' => SORT_DESC])->all();

        $seoBlock = Content::findOne(['id' => 2]);
        //meta
        Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => $seoBlock->getAttribute('meta_description')]);
        Yii::$app->view->registerMetaTag(['name' => 'title', 'content' => $seoBlock->getAttribute('meta_title')]);
        Yii::$app->view->registerMetaTag(['name' => 'keys', 'content' => $seoBlock->getAttribute('meta_keys')]);

        return $this->render('wedd-test', [
            'wedd' => $wedd,
            'seoBlock' => $seoBlock,
        ]);
    }

    public function actionMaleTest()
    {
        Yii::$app->view->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.16/css/bulma.min.css');
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css');
        $male = Test::find()->where(['type' => 2])->orderBy(['sort' => SORT_DESC])->all();

        $seoBlock = Content::findOne(['id' => 2]);
        //meta
        Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => $seoBlock->getAttribute('meta_description')]);
        Yii::$app->view->registerMetaTag(['name' => 'title', 'content' => $seoBlock->getAttribute('meta_title')]);
        Yii::$app->view->registerMetaTag(['name' => 'keys', 'content' => $seoBlock->getAttribute('meta_keys')]);

        return $this->render('male-test', [
            'male' => $male,
            'seoBlock' => $seoBlock,
        ]);
    }

    public function actionFemaleTest()
    {
        Yii::$app->view->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.16/css/bulma.min.css');
        Yii::$app->view->registerCssFile('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css');
        $female = Test::find()->where(['type' => 1])->orderBy(['sort' => SORT_DESC])->all();

        $seoBlock = Content::findOne(['id' => 2]);
        //meta
        Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => $seoBlock->getAttribute('meta_description')]);
        Yii::$app->view->registerMetaTag(['name' => 'title', 'content' => $seoBlock->getAttribute('meta_title')]);
        Yii::$app->view->registerMetaTag(['name' => 'keys', 'content' => $seoBlock->getAttribute('meta_keys')]);

        return $this->render('female-test', [
            'female' => $female,
            'seoBlock' => $seoBlock,
        ]);
    }

//    payment function for registered user

    public function actionPaySystem()
    {
        $request = Yii::$app->request;
        $session = Yii::$app->session;
        if ($request->isPost) {

            $acc = Acc::findOne(['email' => Yii::$app->user->identity->email]);

            $order = new DataOrder();
//        if ($order->validate()) {
            $order->getNewOrder($acc->id);
//            TestResults::addIdOrder(Yii::$app->request->post('test'), $order->order_id);
//        }

            $this->redirect(['/payment/one-pay', 'test' => Yii::$app->request->post('test'), 'order' => $order->order_id]);
        }
    }

    public function successCallback($client)
    {
        $attributes = $client->getUserAttributes();
        $session = Yii::$app->session;
        $auth = Auth::find()->where([
            'source' => $client->getId(),
            'id_source' => $attributes['id'] ? $attributes['id'] : $attributes['user_id'],
        ])->one();

        if (Yii::$app->user->isGuest) {
            if ($auth) { // login
                $user = $auth->user;
                Yii::$app->user->login($user, 3600 * 24 * 30);
                if ($session['auth_url'] == 'invoice') {
                    $session['auth_url'] = '';

views/_block/_footer.php
<?php

/* @var $this yii\web\View */

/**
 * Created by IntelliJ IDEA.
 * User: sandro
 * Date: 29.04.16
 * Time: 14:15
 */
?>
<footer class="footer bg-dark">
    <div class="container-main">
        <div class="logo-footer"><img src="/theme/img/logo_light.svg" alt=""></div>

        <ul class="footer-nav">
            <li><a href="<?= Yii::$app->urlManager->createUrl(['blog/index']) ?>">Блог</a></li>
            <li><a href="<?= Yii::$app->urlManager->createUrl(['site/wedd-test']) ?>">Свадьбы</a></li>
            <li><a href="<?= Yii::$app->urlManager->createUrl(['site/list-test']) ?>">Тесты</a></li>
        </ul>

        <div class="social-links">
            <a href="https://www.facebook.com"><img src="/theme/img/fb_footer.svg" alt=""></a>
            <a href="http://vk.com/imagecorp"><img src="/theme/img/vk_footer.svg" alt=""></a>
            <a href="https://twitter.com/imagecorp?s=09"><img src="/theme/img/tw_footer.svg" alt=""></a>
            <a href="https://www.youtube.com/channel/UCsEOsGrVbvMJvfqgN-vJCtA"><img src="/theme/img/yt_footer.svg" alt=""></a>
        </div>
    </div>
    <p class="copyrights">&copy; 2016 КОРПОРАЦИЯ ИМИДЖА. Онлайн-сервис по подбору имиджа. </p>
</footer>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter37685560 = new Ya.Metrika({
                    id:37685560,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/37685560" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

views/_block/_header.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

/**
 * Created by IntelliJ IDEA.
 * User: sandro
 * Date: 29.04.16
 * Time: 13:51
 */
?>
<div class="header-area">
    <header class="m-header">
        <div class="<?= (Yii::$app->controller->route == 'site/index' || Yii::$app->controller->route == 'site/my-tests' || Yii::$app->controller->route == 'test/result')? 'blog-link':'blog-link style-grey'; ?>">
            <a class="" href="<?= Url::toRoute(['/blog/index']); ?>">Блог</a>
        </div>
        <div class="logo">
            <a href="/"><img src="<?= (Yii::$app->controller->route == 'site/index' || Yii::$app->controller->route == 'site/my-tests' || Yii::$app->controller->route == 'test/result')? '/theme/img/logo_light.svg':'/theme/img/logo_dark.svg'; ?>" alt="Корпорация Имиджа"></a>
        </div>
            <?php
                if(!Yii::$app->user->isGuest){
                    echo '<ul class="user-menu main-page">';
                    echo '<li><a href="' .  Yii::$app->urlManager->createUrl(['dashboard/index']).'">Профиль</a></li>';
                    echo '<li><a href="' .  Yii::$app->urlManager->createUrl(['site/my-tests']).'">Мои тесты</a></li>';
                   echo '<li>' . $url = Html::a('Выйти',
                       ['//user/security/logout'],
                       ['data-method'=>'post']) . '</li>';
//                    echo '<li><a href="' .  Yii::$app->urlManager->createUrl(['user/security/logout']).'">Выйти</a></li>';
                    echo '</ul>';
                    echo '<div class="header-right header-menu m-hidden">';
                    echo '<div class="header-item">';
                    echo '<img src="/' . Yii::getAlias('@avatar') . '/' . Yii::$app->user->identity->avatar . '" alt="">';

                    if(Yii::$app->controller->route == 'site/index' || Yii::$app->controller->route == 'site/my-tests' || Yii::$app->controller->route == 'test/result'){
                        echo '<p class="login-btn">' . Yii::$app->user->identity->username . '</p>';
                    }
                    else{
                        echo '<p class="login-btn style-color">' . Yii::$app->user->identity->username . '</p>';
                    }
                    
                    echo '</div>';
                }
                else{
                    echo '<ul class="user-menu main-page">';
                    echo '<li><a data-toggle="modal" data-target="#login" href="#">Войти</a></li>';
//                    echo '<li><a href="' .  Yii::$app->getUrlManager()->getBaseUrl() . 'user/security/login ">Войти</a></li>';
                    echo '<li><a data-toggle="modal" data-target="#registration" href="#">Зарегистрироваться</a></li>';
//                    echo '<li><a href="' .  Yii::$app->getUrlManager()->getBaseUrl() . 'user/registration/register ">Зарегистрироваться</a></li>';
                    echo '</ul>';
                    echo '<div class="header-right header-menu m-hidden">';
                    echo '<div class="header-item">';
//                    if(Yii::$app->controller->route == 'site/index'){
                        echo '<p class="login-btn">Меню</p>';
//                    }
//                    else{
//                        echo '<p class="login-btn style-color">Меню</p>';
//                    }
                    echo '</div>';
                }
            ?>
        </div>
        <div class="hidden-menu">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </header>
</div>

views/_block/_header_blog.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use common\models\database\BlogCategory;

?>
<header class="blog-header blog-container">
    <div class="top-row">
        <div class="test-link">
            <a href="<?= Yii::$app->urlManager->createUrl(['site/list-test']) ?>" class="head-text hover-prime">Тесты по имиджу</a>
        </div>
        <div class="login-menu">
            <?php
            if (!Yii::$app->user->isGuest) {
                echo '<ul class="user-menu">';
                echo '<li><a href="' . Yii::$app->urlManager->createUrl(['dashboard/index']) . '">Профиль</a></li>';
                echo '<li><a href="' . Yii::$app->urlManager->createUrl(['site/my-tests']) . '">Мои тесты</a></li>';
                echo '<li>' . $url = Html::a('Выйти',
                    ['//user/security/logout'],
                    ['data-method' => 'post']) . '</li>';
                echo '</ul>';
                echo '<div class="login-menu">';
                echo '<img src="/' . Yii::getAlias('@avatar') . '/' . Yii::$app->user->identity->avatar . '" alt="">';
//                if (Yii::$app->controller->route == 'site/index') {
                    echo '<p class="login-btn">' . Yii::$app->user->identity->username . '</p>';
//                } else {
//                    echo '<p class="login-btn style-color">' . Yii::$app->user->identity->username . '</p>';
//                }
            } else {
                echo '<ul class="user-menu">';
                echo '<li><a data-toggle="modal" data-target="#login" href="#">Войти</a></li>';
                echo '<li><a data-toggle="modal" data-target="#registration" href="#">Зарегистрироваться</a></li>';
                echo '</ul>';
                echo '<div class="login-menu">';
                echo '<div class="header-item">';
                if (Yii::$app->controller->route == 'site/index') {
                    echo '<p class="login-btn">Меню</p>';
                } else {
                    echo '<p class="login-btn style-color">Меню</p>';
                }
            }
            echo '</div>';
            echo '</div>';
            ?>
        </div>
    </div>
    <div class="header-logo">
        <a href="/"><img src="/theme/img/logo_light.svg" alt="logo"></a>
    </div>
    <div class="header-nav">
        <div class="blog-link">
            <a href="<?= Url::toRoute(['/blog/index']); ?>" class="head-text hover-prime">БЛОГ</a>
        </div>
        <nav class="main-nav">
            <ul>
                <?php
                $blog_categories = BlogCategory::find()->orderBy(['sort' => SORT_ASC])->all();
                $i = 0;
                foreach ($blog_categories as $item) {
                    $i++;
                    echo '<li><a class="';
                    if (Yii::$app->request->get('category') == $item->category_alias) {
                        echo 'current-link ';
                    }
                    if ($i == 1)
                        echo 'img-link has-subcategory" href="' . Url::toRoute(['/blog/index', 'category' => $item->category_alias]) . '">' . $item->title . '</a></li>';
                    else
                        echo 'img-link" href="' . Url::toRoute(['/blog/index', 'category' => $item->category_alias]) . '">' . $item->title . '</a></li>';
                }
                ?>
            </ul>
        </nav>

        <div class="search">
            <form action="#">
                <input class="search-input" type="text">
                <button class="btn-search" type="submit"></button>
            </form>
        </div>
    </div>
</header>

views/_block/_header_payment.php
<?php
//use Yii;
$this->title = 'Корпорация Имиджа | Тест';

use yii\helpers\Url;
use yii\helpers\Html;
?>
<div class="container">
    <nav class="navbar">
        <!-- Left Side -->
        <div class="navbar-item">
            <span class="icon is-medium"><a href="https://twitter.com/imagecorp?s=09"><i class="fa fa-twitter"></i></a></span>
            <span class="icon is-medium"><a href="https://www.facebook.com"><i class="fa fa-facebook"></i></a></span>
            <span class="icon is-medium"><a href="http://vk.com/imagecorp"><i class="fa fa-vk"></i></a></span>
            <span class="icon is-medium"><a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a></span>
        </div>

        <!-- /Left Side -->
        <!-- Center -->
        <div class="navbar-item is-text-centered">
            <a href="/"><img src="<?= Yii::$app->params['site']; ?>/theme/img/logo.svg" class="logo-svg" alt="Корпорация Имиджа"></a>
        </div>
        <!-- /Center -->
        <!-- Right Side -->
        <?php
        if(!Yii::$app->user->isGuest){
            echo '<ul class="user-menu">';
            echo '<li><a href="' .  Yii::$app->urlManager->createUrl(['dashboard/index']).'">Профиль</a></li>';
            echo '<li><a href="' .  Yii::$app->urlManager->createUrl(['site/my-tests']).'#">Мои тесты</a></li>';
            echo '<li>' . $url = Html::a('Выйти',
                ['//user/security/logout'],
                ['data-method'=>'post']) . '</li>';
//                    echo '<li><a href="' .  Yii::$app->urlManager->createUrl(['user/security/logout']).'">Выйти</a></li>';
            echo '</ul>';
            echo '<div class="header-right header-menu m-hidden">';
            echo '<div class="header-item">';
            echo '<img src="/' . Yii::getAlias('@avatar') . '/' . Yii::$app->user->identity->avatar . '" alt="">';

            if(Yii::$app->controller->route == 'site/index'){
                echo '<p class="login-btn">' . Yii::$app->user->identity->username . '</p>';
            }
            else{
                echo '<p class="login-btn style-color">' . Yii::$app->user->identity->username . '</p>';
            }

            echo '</div>';
        }
        else{
            echo '<ul class="user-menu">';
            echo '<li><a data-toggle="modal" data-target="#login" href="#">Войти</a></li>';
//                    echo '<li><a href="' .  Yii::$app->getUrlManager()->getBaseUrl() . 'user/security/login ">Войти</a></li>';
            echo '<li><a data-toggle="modal" data-target="#registration" href="#">Зарегистрироваться</a></li>';
//                    echo '<li><a href="' .  Yii::$app->getUrlManager()->getBaseUrl() . 'user/registration/register ">Зарегистрироваться</a></li>';
            echo '</ul>';
            echo '<div class="header-right header-menu m-hidden">';
            echo '<div class="header-item">';
            if(Yii::$app->controller->route == 'site/index'){
                echo '<p class="login-btn">Меню</p>';
            }
            else{
                echo '<p class="login-btn style-color">Меню</p>';
            }
            echo '</div>';
        }
        ?>
<!--        <div class="navbar-item is-text-right accent normal text_1">-->
<!--            <a href="#">Войти</a> или-->
<!---->
<!--            <a href="#">Зарегистрироваться</a>-->
<!--        </div>-->
        <!-- /Right Side -->

    </nav>
</div>

views/_block/_register.php
<?php
use yii\helpers\Html;
use yii\web\JsExpression;
use dektrium\user\models\RegistrationForm;

$model = Yii::createObject(RegistrationForm::className());

/**
 * @var yii\web\View              $this
 * @var yii\widgets\ActiveForm    $form
 * @var dektrium\user\models\User $user
 */
?>
    <p class="control">
        <?= Html::activeTextInput($model, 'username', ['placeholder' => 'Логин', 'type' => 'text', 'class' => 'input is-medium']); ?>
        <?= Html::error($model, 'username'); ?>
    </p>
    <p class="control">
        <?= Html::activeTextInput($model, 'email', ['placeholder' => 'E-mail', 'type' => 'email', 'class' => 'input is-medium']); ?>
        <?= Html::error($model, 'email'); ?>
    </p>
    <p class="control">
        <?= Html::activeTextInput($model, 'password', ['placeholder' => 'Пароль', 'type' => 'password', 'class' => 'input is-medium']); ?>
        <?= Html::error($model, 'password'); ?>
    </p>
<input name="test" type="hidden" value="<?= Yii::$app->request->get('test')?>" class="input is-medium" />

<input type="hidden" name="DataOrder[summ]" value="100" id="summ" />
<input type="hidden" name="DataOrder[for]"  value="<?= Yii::$app->request->get('test'); ?>"/>
<input type="hidden" name="DataOrder[user]" value="<?= Yii::$app->user->id; ?>"/>

views/_block/_slider.php
<?php

use common\models\database\Slider;
use common\models\database\Test;
use common\models\database\Gallery;

/* @var $this yii\web\View */

/**
 * Created by IntelliJ IDEA.
 * User: sandro
 * Date: 29.04.16
 * Time: 14:08
 */

?>
<div id="carousel_main" class="carousel slide main-slider" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        <?php
            $slides = [];
            $i = 0;
            foreach (unserialize(Slider::findOne(['id' => 1])->image_id) as $item) {
                $img = Gallery::findOne(['id' => (int)$item]);
                $data = Test::findOne(['id' => (int)$img->data]);
                if($data){
                    echo '<div style="background-image: url('.$img->src.')" class="item top-slide-'.$i.' top-slide';
                    if($i == 0){
                        echo ' active';
                    }
                    echo '">';
                    echo '<div class="flex-wrap">';
                    echo '<div class="tests">';
                    echo '<h2 class="slide-title">'.$data->title.'</h2>';
                    echo '<p class="slide-text">';
                    echo $data->description;
                    echo '</p>';
                    echo '<div class="btns-wrap">';
                    echo '<a href="' . Yii::$app->urlManager->createUrl(['site/female-test']) . '" class="btn-female">ЖЕНЩИНА</a>';
                    echo '<a href="' . Yii::$app->urlManager->createUrl(['site/male-test']) . '" class="btn-male">МУЖЧИНА</a>';
                    echo '</div>';
                    echo '<p class="likes"><span class="likes-count">'.$data->like.'</span></p>';
                    echo '<a class="left carousel-control" href="#carousel_main" role="button" data-slide="prev">';
                    echo '<span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>';
                    echo '<span class="sr-only">Previous</span>';
                    echo '</a>';
                    echo '<a class="right carousel-control" href="#carousel_main" role="button" data-slide="next">';
                    echo '<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>';
                    echo '<span class="sr-only">Next</span>';
                    echo '</a>';
                    echo '</div>';
                    echo '</div>';
                    echo '</div>';
                    $i++;
                }
            }
        ?>
    </div>
</div>